name: Testes Go

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configura Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Verifica dependÃªncias
        run: go mod tidy

      - name: Executa testes com cobertura
        run: |
          go test ./...
          
