name: Test - Go

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [ '1.22', '1.23', '1.24']
    name: Test - Go ${{ matrix.version }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configura Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.version }}
          cache-dependency-path: go.mod

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.mod') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Verifica dependÃªncias
        run: go mod tidy

      - name: Executa testes com cobertura
        run: |
          go test ./...
          
